#!/sbin/openrc-run
# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command=/usr/bin/uvicorn
command_args="etebase_server.asgi:application --app-dir /usr/@LIBDIR@/etebase-server"
command_args+=" --port ${ETEBASE_PORT:-8000} --host ${ETEBASE_HOST:-127.0.0.1}"
pidfile="/run/etebase-server.pid"
command_background=true
command_user="etebase:etebase"
